cpu-bind=MASK - gn30, task  1  0 [2504020]: mask 0xffff0000ffff0000ffffffffffffffffffff0000ffff0000ffffffffffffffff set
*******STARTING********
--- Running on Node Rank: 1 ---
Total Nodes: 2
--- CUDA_VISIBLE_DEVICES for this srun task: 0,1,2,3 ---
GPUs per Node: 4
Master Address: gn21
Master Port: 29500
-------------------------------------------
accelerate launch     --config_file /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/accelerate_config.yaml     --num_machines 2     --machine_rank 1     --main_process_ip gn21     --main_process_port 29500     --num_processes 8     --deepspeed_hostfile /ceph/hpc/data/s24o01-42-users/translation_optimization/trl/result_dir/hostfile_62084318     --deepspeed_multinode_launcher standard     --rdzv_backend static     --same_network     --mixed_precision bf16     "train.py"     --rank=64 --learning_rate=3e-7 --total_epochs=3 --beta=0.2
-------------------------------------------
[2025-05-31 02:22:11,153] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
W0531 02:22:13.093000 2504066 torch/distributed/run.py:792] 
W0531 02:22:13.093000 2504066 torch/distributed/run.py:792] *****************************************
W0531 02:22:13.093000 2504066 torch/distributed/run.py:792] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0531 02:22:13.093000 2504066 torch/distributed/run.py:792] *****************************************
[2025-05-31 02:22:18,174] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 02:22:18,209] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 02:22:18,225] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-05-31 02:22:18,233] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
World size: 8
Setting gradient accumulation steps to: 2
Created datasets
Number of training examples: 8564
Number of validation examples: 953
Namespace(rank=64, learning_rate=3e-07, total_epochs=3, beta=0.2)
3e-07
[2025-05-31 02:22:21,405] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-31 02:22:21,448] [INFO] [comm.py:658:init_distributed] cdb=None
Created datasets
Steps per epoch: 4282
Eval steps: 2141
[2025-05-31 02:22:21,454] [INFO] [comm.py:658:init_distributed] cdb=None
[2025-05-31 02:22:21,461] [INFO] [comm.py:658:init_distributed] cdb=None
Set up DPO configuration
[2025-05-31 02:22:23,372] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[2025-05-31 02:22:23,372] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[2025-05-31 02:22:23,372] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[2025-05-31 02:22:23,372] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:08,  2.99s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:08,  2.98s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:08,  2.99s/it]Loading checkpoint shards:  25%|██▌       | 1/4 [00:02<00:08,  2.99s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:09<00:10,  5.25s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:09<00:10,  5.25s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:09<00:10,  5.25s/it]Loading checkpoint shards:  50%|█████     | 2/4 [00:09<00:10,  5.25s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.82s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.82s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.82s/it]Loading checkpoint shards:  75%|███████▌  | 3/4 [00:16<00:05,  5.82s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.31s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.31s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.21s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.31s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.21s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.31s/it]Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.21s/it]
Loading checkpoint shards: 100%|██████████| 4/4 [00:20<00:00,  5.21s/it]
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
[2025-05-31 02:22:59,016] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[rank7]: Traceback (most recent call last):
[rank7]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank7]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank7]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 144, in main
[rank7]:     ref_model = model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation="eager")   # Reference model for DPO
[rank7]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank7]:     return model_class.from_pretrained(
[rank7]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank7]:     return func(*args, **kwargs)
[rank7]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank7]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank7]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank7]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 978, in __init__
[rank7]:     groups._create_zero_param_parallel_group(_ds_config.zero_config.zero_hpz_partition_size)
[rank7]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/groups.py", line 663, in _create_zero_param_parallel_group
[rank7]:     assert _ZERO_PARAM_INTRA_PARALLEL_GROUP is None, \
[rank7]: AssertionError: ZeRO parameter intra parallel group is already initialized
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loaded model
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:631: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/generation/configuration_utils.py:636: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
[2025-05-31 02:22:59,113] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[rank6]: Traceback (most recent call last):
[rank6]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank6]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank6]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 144, in main
[rank6]:     ref_model = model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation="eager")   # Reference model for DPO
[rank6]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank6]:     return model_class.from_pretrained(
[rank6]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank6]:     return func(*args, **kwargs)
[rank6]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank6]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank6]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank6]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 978, in __init__
[rank6]:     groups._create_zero_param_parallel_group(_ds_config.zero_config.zero_hpz_partition_size)
[rank6]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/groups.py", line 663, in _create_zero_param_parallel_group
[rank6]:     assert _ZERO_PARAM_INTRA_PARALLEL_GROUP is None, \
[rank6]: AssertionError: ZeRO parameter intra parallel group is already initialized
[2025-05-31 02:22:59,171] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[rank5]: Traceback (most recent call last):
[rank5]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank5]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank5]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 144, in main
[rank5]:     ref_model = model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation="eager")   # Reference model for DPO
[rank5]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank5]:     return model_class.from_pretrained(
[rank5]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank5]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank5]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank5]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 978, in __init__
[rank5]:     groups._create_zero_param_parallel_group(_ds_config.zero_config.zero_hpz_partition_size)
[rank5]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/groups.py", line 663, in _create_zero_param_parallel_group
[rank5]:     assert _ZERO_PARAM_INTRA_PARALLEL_GROUP is None, \
[rank5]: AssertionError: ZeRO parameter intra parallel group is already initialized
[2025-05-31 02:22:59,371] [INFO] [config.py:734:__init__] Config mesh_device None world_size = 8
[rank4]: Traceback (most recent call last):
[rank4]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 207, in <module>
[rank4]:     main(train_data, val_data, args.rank, args.learning_rate, args.total_epochs, args.beta)
[rank4]:   File "/ceph/hpc/data/s24o01-42-users/translation_optimization/trl/train.py", line 144, in main
[rank4]:     ref_model = model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation="eager")   # Reference model for DPO
[rank4]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 571, in from_pretrained
[rank4]:     return model_class.from_pretrained(
[rank4]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 279, in _wrapper
[rank4]:     return func(*args, **kwargs)
[rank4]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4332, in from_pretrained
[rank4]:     model_init_context = cls.get_init_context(is_quantized, _is_ds_init_called)
[rank4]:   File "/ceph/hpc/home/dv70648/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3727, in get_init_context
[rank4]:     init_contexts.extend([deepspeed.zero.Init(config_dict_or_path=deepspeed_config()), set_zero3_state()])
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 978, in __init__
[rank4]:     groups._create_zero_param_parallel_group(_ds_config.zero_config.zero_hpz_partition_size)
[rank4]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/groups.py", line 663, in _create_zero_param_parallel_group
[rank4]:     assert _ZERO_PARAM_INTRA_PARALLEL_GROUP is None, \
[rank4]: AssertionError: ZeRO parameter intra parallel group is already initialized
W0531 02:23:03.834000 2504066 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2504338 closing signal SIGTERM
W0531 02:23:03.835000 2504066 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2504339 closing signal SIGTERM
W0531 02:23:03.835000 2504066 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2504340 closing signal SIGTERM
E0531 02:23:04.049000 2504066 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 3 (pid: 2504341) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1182, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 861, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-31_02:23:03
  host      : pm5-nod93.vega.pri
  rank      : 7 (local_rank: 3)
  exitcode  : 1 (pid: 2504341)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
